project:
  type: website
  resources:
    - .well-known/*

filters:
  - quarto
  - strip-xref-numbers.lua

execute:
  freeze: auto

website:
  title: Theo Pomies
  site-url: https://theopomies.com
  description: |
    I'm a software engineer and entrepreneur. Currently working on my startup, Kivala, a new kind of interphone and digicode.
    I'm also tryharding AI/ML, from the research to the production (math, kernels, training, inference, deployment, etc.).
    This is where I try to dump my notes and thoughts, throughout the learning journey.
  favicon: img/favicon.ico
  navbar:
    title: false
    # collapse: false
    # tools-collapse: false
    background: $body-bg
    color: $body-color
    left:
      - href: index.qmd
        text: about me
      - href: posts/index.qmd
        text: posts
      - href: notes/index.qmd
        text: notes
      - href: journal/index.qmd
        text: journal
    tools:
      - icon: twitter-x
        href: https://x.com/theopomies
        target: _blank
      - icon: github
        href: https://github.com/theopomies
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/theopomies/
        target: _blank
  twitter-card: true

format:
  html:
    theme:
      dark:
        - theopoimandres.scss
        - styles.scss
      light:
        - theopoimandres-light.scss
        - styles.scss
    toc: true
    highlight-style:
      dark: theopoimandres.theme
      light: theopoimandres-light.theme
