---
title: Finished reading The Manga Guide to Linear Algebra
description: Learning more about Linear Transformations, Eigen{vectors, values} and Diagonalization
categories: [math]
date: 2025-09-01
---

I had a lot of work to do for my day job, we are trying to build and commercialize V2 of [our intercom system](https://www.kivala.fr){target=_blank}, and I was faced with technical difficulties that left me very little time to work on math / ML. I still found the time to finish The Manga Guide to Linear Algebra, and learned a few important concepts and techniques!

### Still, I did a _few_ things

TIL about [subspaces], [linear spans], the [rank] of a matrix and a technique to find it via [Gaussian Eliminination](/notes/linear-algebra.html#sec-gaussian-elimination) — as usual, linear algebra appears to be the art of applying Gaussian Elimination correctly —, [Eigenvalues] and [Eigenvectors]! That was still packed!

I skimmed through the materials for [Scratch To Scale](https://maven.com/walk-with-code/scratch-to-scale){target=_blank}, the course I'm following by [Scott Mueller](https://x.com/thezachmueller){target=_blank}, beginning tomorrow.
