---
title: Marimo Workshop + Integrals refresher
description: A superb Marimo workshop with Vincent Warmerdam (S2S) and binge watching Essence Of Calculus (3b1b)
categories: [python, math]
date: 2025-09-08
---

### Binge watched Essence of Calculus

After digging back into probabilities, I realized how important it was that I not only know [integrals](/notes/calculus.qmd#integrals) and formulas, but also that I completely _grok_ and am able to derive these formulas from first principles. So I re-watched the entire [Essence of Calculus](https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr){target=_blank} series by the incredible [3b1b / Grant Sanderson](https://www.youtube.com/@3blue1brown){target=_blank}.

And grokking I did, between the videos and my old high-school and college lessons somewhere hidden deep inside my mind, I feel a renewed understanding of integration, so I wrote notes for the future me that will obviously forget again.

### Some more Linear Algebra

Some research into the basics — first principles always wins — led me to learn about [Elementary Matrices](/notes/linear-algebra.qmd#elementary-matrix). I'd never given more thought to Gaussian Elimination that just using the row operations to achieve my goal. But thinking about elementary matrices and their properties, made things like [LU decomposition](/notes/linear-algebra.qmd#lu-decomposition-or-lu-factorization) click even more.

### Marimo Workshop

To finish off this awesome day of learning, we had a workshop with [Vincent Warmerdam](https://koaning.io/){target=_blank} from the [Marimo](https://marimo.io){target=_blank} team. I love marimo and I loved learning more about it's capabilities and ways to hack (with / at) it.
